### ISSUE TITLE
HiveServer2 thrift code generation issue

### ISSUE THREAD

**Issue by ajithj** [tanmaykm/Thrift.jl#15]
I used TCLIService.thrift from Hive to generate julia bindings.

https://github.com/apache/hive/blob/aed350351b24125ff6bbf36373b5247070c48d5c/service-rpc/if/TCLIService.thrift

-The generated file has some line(s) truncated
TCLIService.jl:

include("TCLIService_constants.jl")
include("TCLIService_types.jl")
include("TCLIService_impl.jl")  # server methods to be hand coded
include("TCLIService.jl")

end # module TCLIService
 fillunset(o); o)
  GetTables_result(success) = (o=new(); fillset(o, :success); o.success=success; o)
end # type GetTables_result
meta(t::Type{GetTables_result}) = meta(t, Symbol[:success], Int[0], Dict{Symbol,Any}())

-There is an include statement for TCLIService_impl.jl, however that file never got generated.

**Comment by tanmaykm** [comment]
The file `*_impl.jl` files are for implementing server code. They can't be generated from the specification files. The generated source already mentions: `# server methods to be hand coded` beside the include statement.

Do look into the `test` folder to see some examples.
You may also find https://github.com/JuliaDB/Hive.jl related.

**Comment by ajithj** [comment]
[TCLIService.zip](https://github.com/tanmaykm/Thrift.jl/files/314876/TCLIService.zip)

Hi Tanmay,
hand coding impl file is fine. However there is one more issue. 
Please see the TCLIservice.jl file attached. After the module definition look for the first line [fillunset(o); o)]
I think that is supposed to be within a type definition. There is a line or 2 missing there.

**Comment by tanmaykm** [comment]
Hi @ajithj, in `TCLIService.thrift` there's a service named `TCLIService` defined. The code generator generates both the service and the module as `TCLIService.jl` and overwrites one with the other.

You could avoid that by renaming `TCLIService.thrift` to `Hive` or `HS2` or something similar.

Ideally, the code generator should warn instead of overwriting, but a check for that is not implemented yet. That would likely be a change in `compiler/t_jl_generator.cc`.

**Comment by ajithj** [comment]
Thank you!
